### ISSUE TITLE
Version 0.8 breaks --ignore-paths CLI option

### ISSUE THREAD

**Issue by kevinvalk** [samuelcolvin/watchgod#100]
After upgrading to 0.8 I got the following error
```
[15:25:04] watching "/app" and reloading "celery.__main__.main" on changes...
'import warnings' failed; traceback:
KeyboardInterrupt
/venv/lib/python3.10/site-packages/kombu/utils/compat.py:82: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  for ep in importlib_metadata.entry_points().get(namespace, [])
[15:25:09] process has not terminated, sending SIGKILL
Traceback (most recent call last):
  File "/venv/bin/watchgod", line 8, in <module>
    sys.exit(cli())
  File "/venv/lib/python3.10/site-packages/watchgod/cli.py", line 139, in cli
    run_process(
  File "/venv/lib/python3.10/site-packages/watchgod/main.py", line 188, in run_process
    for changes in watch(
  File "/venv/lib/python3.10/site-packages/watchgod/main.py", line 43, in watch
    yield anyio.run(_awatch.__anext__)
  File "/venv/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 56, in run
    return asynclib.run(func, *args, **backend_options)
  File "/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 233, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 228, in wrapper
    return await func(*args)
  File "/venv/lib/python3.10/site-packages/watchgod/main.py", line 99, in __anext__
    watcher = self._w = await self.run_in_executor(
  File "/venv/lib/python3.10/site-packages/watchgod/main.py", line 143, in run_in_executor
    return await anyio.to_thread.run_sync(func, *args, limiter=self._thread_limiter)
  File "/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
TypeError: PythonWatcher.__init__() got an unexpected keyword argument 'ignore_paths'
someservice exited with code 1
```

To me it seems this is due to misspell on line: 
https://github.com/samuelcolvin/watchgod/blob/63a49658f8ded07c7e79278d20a71398e7a762e2/watchgod/cli.py#L133

Specifically, if you look at the diff https://github.com/samuelcolvin/watchgod/compare/v0.7...v0.8#diff-716db2f16f170e5b4160957ed276c8768ce804fb889f26c2c3fd48b08a551062R133 you see the watcher kwargs previously was `ignored_paths` (note the **d** in ignore**d**)

Could you verify if this is a bug, or if the CLI for the `--ignore-paths` option has changed?

**Comment by samuelcolvin** [comment]
should be fixed in #101. @kevinvalk, any chance you could check that PR fixes your issue and I'll release a patch.
