### ISSUE TITLE
Running in docker-compose results in no /dev/tty

### ISSUE THREAD

**Issue by elatt** [samuelcolvin/watchgod#40]
If I try and run the `watchgod` CLI with my app in a docker-compose environment, it will fail due to the lack of `/dev/tty` being present:
```
web_1          | [02:48:45] watching "/app/" and reloading "app.main" on changes...
web_1          | Process Process-1:
web_1          | Traceback (most recent call last):
web_1          |   File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
web_1          |     self.run()
web_1          |   File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
web_1          |     self._target(*self._args, **self._kwargs)
web_1          |   File "/usr/local/lib/python3.7/site-packages/watchgod/cli.py", line 45, in run_function
web_1          |     with set_tty(tty_path):
web_1          |   File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
web_1          |     return next(self.gen)
web_1          |   File "/usr/local/lib/python3.7/site-packages/watchgod/cli.py", line 36, in set_tty
web_1          |     with open(tty_path) as tty:
web_1          | OSError: [Errno 6] No such device or address: '/dev/tty'
```
By default `docker-compose up` doesn't configure a TTY (but `docker-compose run` does) and while this can be [configured](https://docs.docker.com/compose/compose-file/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir) does watchgod really need to require a TTY?

**Comment by samuelcolvin** [comment]
yup, try #42 and let me know if that fixes it.
